name: Build Debian Packages

on:
  workflow_dispatch:
    inputs:
      slurmVersion:
        description: Slurm distributive version
        required: true
        default: 24.11.5
        type: string

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Latest Tag
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag

      - name: Build
        run: |
          sudo apt-get update
          sudo apt-get install -y curl lbzip2 build-essential fakeroot devscripts equivs libnvidia-ml-dev libmunge-dev
          curl -O https://download.schedmd.com/slurm/slurm-$SLURM_VERSION.tar.bz2
          tar -xf slurm-$SLURM_VERSION.tar.bz2
          cd slurm-$SLURM_VERSION
          patch < ../slurm.diff
          sudo mk-build-deps -i debian/control -t 'apt-get -y -o Debug::pkgProblemResolver=yes --no-install-recommends'
          debuild -b -uc -us
        shell: bash
        env:
          SLURM_VERSION: ${{ inputs.slurmVersion }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ inputs.slurmVersion }} bld-${{ github.run_id }}
          body: SLURM ${{ inputs.slurmVersion }} release
          files: slurm*.deb
          tag_name: ${{ steps.get-latest-tag.outputs.tag }}