name: Build Debian Packages

on:
  workflow_dispatch:
    inputs:
      ofedVersion:
        description: OFED version
        required: true
        default: 23.10-2.1.3.1
        type: string
      slurmVersion:
        description: Slurm version
        required: true
        default: 24.11.5
        type: string
      openmpiVersion:
        description: OpenMPI version
        required: true
        default: 4.1.7a1
        type: string
      openmpiSubVersion:
        description: OpenMPI sub version
        required: true
        default: "1.2310055"
        type: string

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Latest Tag
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag

      - name: Build
        run: |
          sudo wget -O /etc/apt/sources.list.d/mellanox_mlnx_ofed.list https://linux.mellanox.com/public/repo/mlnx_ofed/${OFED_VERSION}/ubuntu22.04/mellanox_mlnx_ofed.list
          wget -qO - https://www.mellanox.com/downloads/ofed/RPM-GPG-KEY-Mellanox | sudo apt-key add -
          sudo apt-get update
          
          sudo apt-get install -y curl lbzip2 build-essential fakeroot devscripts equivs \
            openmpi=${OPENMPI_VERSION}-${OPENMPI_SUBVERSION} \
            libnvidia-ml-dev munge libmunge-dev libpmix2 libpmix-dev libevent-dev
          
          export PATH=$PATH:/usr/mpi/gcc/openmpi-${OPENMPI_VERSION}/bin
          
          curl -O https://download.schedmd.com/slurm/slurm-$SLURM_VERSION.tar.bz2
          tar -xf slurm-$SLURM_VERSION.tar.bz2
          cd slurm-$SLURM_VERSION
          sed -i "s|--with-pmix\b|--with-nvml --with-pmix=/usr/lib/${ARCH}-linux-gnu/pmix2|" debian/rules
          sudo mk-build-deps -i debian/control -t 'apt-get -y -o Debug::pkgProblemResolver=yes --no-install-recommends'
          debuild -b -uc -us
        shell: bash
        env:
          SLURM_VERSION: ${{ inputs.slurmVersion }}
          OFED_VERSION: ${{ inputs.ofedVersion }}
          OPENMPI_VERSION: ${{ inputs.openmpiVersion }}
          OPENMPI_SUBVERSION: ${{ inputs.openmpiSubVersion }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: "SLURM ${{ inputs.slurmVersion }} (build: ${{ github.run_id }})"
          body: SLURM ${{ inputs.slurmVersion }} release
          files: slurm*.deb
          tag_name: ${{ steps.get-latest-tag.outputs.tag }}